#!/bin/bash
set -e

source .env

if [ $# -eq 0 ]
  then
    docker-compose exec postgres-12 psql -h postgres-12 -U postgres postgres
  else
    docker-compose exec postgres-12 psql -h postgres-12 -U postgres postgres $1
fi

