#!/bin/bash
set -e

source .env

if [ $# -eq 0 ]
  then
    docker-compose exec postgres-12 psql -h postgres-12 -U ${POSTGRES_USER} ${POSTGRES_USER}
  else
    docker-compose exec postgres-12 psql -h postgres-12 -U ${POSTGRES_USER} ${POSTGRES_USER} $1
fi

