#!/bin/bash
set -e

if [ $# -eq 0 ]
  then
    ./env-prepare && docker-compose -f ./docker-compose.build.yml build
  else
    ./env-prepare && docker-compose -f ./docker-compose.build.yml build $1
fi



