version: '3'

services:

  postgres-13-rdkit-2021-03:
    image: chembience/postgres-rdkit:${BUILD_TAG_POSTGRES_13_RDKIT_2021_03}
    build:
      context: 13/
      args:
        build_tag: ${BUILD_TAG_POSTGRES_13_RDKIT_2021_03}
        rdkit_sql: ${RDKIT_SQL_2021_03}
    depends_on:
      - rdkit-2021-03

  rdkit-2021-03:
    image: chembience/postgres-rdkit-compile:${BUILD_TAG_POSTGRES_13_RDKIT_2021_03}
    build:
      context: 13/rdkit-2021-03
      args:
        build_tag: ${BUILD_TAG_POSTGRES_13_RDKIT_2021_03}
        rdkit_branch: ${RDKIT_BRANCH_2021_03}

  postgres-13-rdkit-2020-09:
    image: chembience/postgres-rdkit:${BUILD_TAG_POSTGRES_13_RDKIT_2020_09}
    build:
      context: 13/
      args:
        build_tag: ${BUILD_TAG_POSTGRES_13_RDKIT_2020_09}
        rdkit_sql: ${RDKIT_SQL_2020_09}
    depends_on:
      - rdkit-2020-09

  rdkit-2020-09:
      image: chembience/postgres-rdkit-compile:${BUILD_TAG_POSTGRES_13_RDKIT_2020_09}
      build:
        context: 13/rdkit-2020-09
        args:
          build_tag: ${BUILD_TAG_POSTGRES_13_RDKIT_2020_09}
          rdkit_branch: ${RDKIT_BRANCH_2020_09}


  postgres-rdkit-12:
    image: chembience/postgres-rdkit:${BUILD_TAG_12}
    build:
      context: 12/
      args:
        build_tag: ${BUILD_TAG_12}
        rdkit_sql: ${RDKIT_SQL_12}
    depends_on:
      - rdkit-12

  rdkit-12:
    image: chembience/postgres-rdkit-compile:${BUILD_TAG_12}
    build:
      context: 12/rdkit
      args:
        build_tag: ${BUILD_TAG_12}
        rdkit_branch: ${RDKIT_BRANCH_12}


  postgres-rdkit-11:
    image: chembience/postgres-rdkit:${BUILD_TAG_11}
    build:
      context: 11/
      args:
        build_tag: ${BUILD_TAG_11}
        rdkit_sql: ${RDKIT_SQL_11}
    depends_on:
      - rdkit-11

  rdkit-11:
    image: chembience/postgres-rdkit-compile:${BUILD_TAG_11}
    build:
      context: 11/rdkit
      args:
        build_tag: ${BUILD_TAG_11}
        rdkit_branch: ${RDKIT_BRANCH_11}


