#!/bin/bash
set -e

source .env

if [ $# -eq 0 ]
  then
    docker-compose exec postgres psql -h postgres -U postgres postgres
  else
    docker-compose exec postgres psql -h postgres -U postgres postgres $1
fi

