version: '3'

services:

  postgres-13:
    image: chembience/postgres-rdkit:postgres-13.rdkit-2021.03
    container_name: postgres-13-rdkit-2021.03
    volumes:
      - postgres_rdkit_db_volume_13:/var/lib/postgresql
    networks:
      - sphere
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER

volumes:
  postgres_rdkit_db_volume_13:

networks:
  sphere:
