name: Docker

on:
  push:
    branches:
      - master
      - ci
    tags:
      - v*

  pull_request:

#env:
#  # TODO: Change variable to your image's name.
#  IMAGE_NAME: postgres-rdkit:postgres-13.rdkit-2020.09

jobs:

  push:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Prepare env
        run: ./env-prepare

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: "markussitzmann"
          password: ${{ secrets.DOCKER_PASSWD }}

      - name: Build image
        run: docker-compose --file docker-compose.build.yml build rdkit-13 postgres-rdkit-13

      - name: Push image
        run: |
           docker-compose --file docker-compose.build.yml push postgres-rdkit-13

          
