name: Docker

on:
  push:
    branches:
      #- master
      - ci
    tags:
      - v*

  pull_request:


jobs:

  push:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Prepare env
        run: ./env-prepare

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: "markussitzmann"
          password: ${{ secrets.DOCKER_PASSWD }}

      - name: Build Postgres 11 Image
        run: docker-compose --file docker-compose.build.yml build rdkit-11 postgres-rdkit-11

      - name: Push Image
        run: |
           docker-compose --file docker-compose.build.yml push postgres-rdkit-11

          
